title: Test Environment
description: An environment configured to test my work.
theme: just-the-docs

url: https://VidhyaDivakar.github.io/TestEnvironment

plugins:
  - jekyll-default-layout

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
